/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptech.myexpensesswing;

import com.bsptechs.entities.User;
import com.bsptechs.service.impl.UserService;
import com.bsptechs.service.inter.IUserService;



/**
 *
 * @author Anar Salami
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        mnMain = new javax.swing.JMenuBar();
        mnUser = new javax.swing.JMenu();
        mnExpenses = new javax.swing.JMenu();
        mnExpenseType = new javax.swing.JMenu();
        mnExpenseCatagory = new javax.swing.JMenu();
        mnRoles = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        mnUser.setText("User");
        mnUser.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnUserMenuSelected(evt);
            }
        });
        mnMain.add(mnUser);

        mnExpenses.setText("Expenses");
        mnExpenses.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnExpensesMenuSelected(evt);
            }
        });
        mnMain.add(mnExpenses);

        mnExpenseType.setText("Expense Type");
        mnExpenseType.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnExpenseTypeMenuSelected(evt);
            }
        });
        mnMain.add(mnExpenseType);

        mnExpenseCatagory.setText("Expense Catagory");
        mnExpenseCatagory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnExpenseCatagoryMenuSelected(evt);
            }
        });
        mnMain.add(mnExpenseCatagory);

        mnRoles.setText("Roles");
        mnRoles.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnRolesMenuSelected(evt);
            }
        });
        mnRoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnRolesKeyPressed(evt);
            }
        });
        mnMain.add(mnRoles);

        setJMenuBar(mnMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    IUserService iu = new UserService();
    public  void components(int roleId) {
        if (roleId == 2) {
            this.setVisible(true);
            mnMain.remove(mnExpenseType);
            mnMain.remove(mnUser);
            mnMain.remove(mnRoles);
        }
    }

    private void mnUserMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnUserMenuSelected
        this.setVisible(false);
        new UsersWindow().setVisible(true);
    }//GEN-LAST:event_mnUserMenuSelected

    private void mnExpensesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnExpensesMenuSelected
        this.setVisible(false);
        new ExpenseWindow().setVisible(true);
    }//GEN-LAST:event_mnExpensesMenuSelected

    private void mnExpenseTypeMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnExpenseTypeMenuSelected
        this.setVisible(false);
        new ExpenseTypeWindow().setVisible(true);
    }//GEN-LAST:event_mnExpenseTypeMenuSelected

    private void mnExpenseCatagoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnExpenseCatagoryMenuSelected
        this.setVisible(false);
        new ExpenseCategoryWindow().setVisible(true);
    }//GEN-LAST:event_mnExpenseCatagoryMenuSelected

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.setVisible(false);
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void mnRolesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnRolesKeyPressed

    }//GEN-LAST:event_mnRolesKeyPressed

    private void mnRolesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnRolesMenuSelected
        this.setVisible(false);
        new Roles().setVisible(true);
    }//GEN-LAST:event_mnRolesMenuSelected

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        User user = new User();
        if (user.getRoleId().getId() == 1) {
            mnUser.remove(mnExpenseCatagory);
            mnUser.remove(mnRoles);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JMenu mnExpenseCatagory;
    private javax.swing.JMenu mnExpenseType;
    private javax.swing.JMenu mnExpenses;
    private javax.swing.JMenuBar mnMain;
    private javax.swing.JMenu mnRoles;
    private javax.swing.JMenu mnUser;
    // End of variables declaration//GEN-END:variables
}
